### ISSUE TITLE
Document roadmap management in the governance documentation and contribution guidelines

### ISSUE THREAD

**Issue by slashben** [kubescape/project-governance#3]
Create a document that describes how to read the roadmap, including explanations on roadmap lifecycle and explanations on how to create issues that link to it.

**Comment by Oshratn** [comment]
Per the [CNCF Guidelines on roadmaps](https://contribute.cncf.io/maintainers/community/contributor-growth-framework/open-source-roadmaps/) I did a review of all the repos in Kubescape and have some questions and comments:

Shouldn't the private repos be removed/archived?

Also, the guidelines state that each repo should have a clear README. In our case there are dramatic inconsitencies between the repos in the Kubescape org. Following is a list, with groupings of repos that need to be addressed:

### README missing 

- [ ] https://github.com/[kubescape/backstage-plugin](https://github.com/kubescape/backstage-plugin)
- [ ] https://github.com/kubescape/rbac-utils
- [ ] https://github.com/kubescape/opa-utils
- [ ] https://github.com/[kubescape/update-test-repo-1](https://github.com/kubescape/update-test-repo-1)
- [ ] https://github.com/[kubescape/roadmap](https://github.com/kubescape/roadmap)

### README is or seems incomplete or outdated

- [ ] https://github.com/kubescape/helm-charts
- [ ] https://github.com/kubescape/k8s-interface
- [ ] https://github.com/kubescape/helm-release-upgrader
- [ ] https://github.com/kubescape/messaging
- [ ] https://github.com/kubescape/http-request
- [ ] https://github.com/[kubescape/ebpf-engine](https://github.com/kubescape/ebpf-engine)
- [ ] https://github.com/[kubescape/sarif-demo](https://github.com/kubescape/sarif-demo)

### Typos or light editing required

- [x] https://github.com/kubescape/project-governance
- [ ] https://github.com/[kubescape/YAML-examples](https://github.com/kubescape/YAML-examples)
- [ ] https://github.com/[kubescape/juju-kubescape](https://github.com/kubescape/juju-kubescape)
- [ ] https://github.com/[kubescape/node-yamlparse](https://github.com/kubescape/node-yamlparse)
- [ ] https://github.com/kubescape/node-kubescape

### TODOs in README and not on ROADMAP or Issues list

- [ ] https://github.com/[kubescape/backend](https://github.com/kubescape/backend)
- [ ] https://github.com/kubescape/kubescape-network-scanner
- [ ] https://github.com/kubescape/regolibrary-playground

### Belongs somewhere in governance documentation

- [ ] https://github.com/kubescape/workflows

@Oshratn can take care of the typos and light editing, all the rest needs more skills than I have.

**Comment by Oshratn** [comment]
Related PRs:
https://github.com/kubescape/node-kubescape/pull/8
https://github.com/kubescape/juju-kubescape/pull/2
https://github.com/kubescape/node-yamlparse/pull/5
https://github.com/kubescape/YAML-examples/pull/14
